{{ if hasKey .Values "host" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.host | replace "." "-" }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: {{ .Values.path | default "/" }}(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Chart.Name }}
            port: 
              number: {{ .Values.port }}
{{ end }}