apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: safesecrets-controller-role
rules:
- apiGroups: ["janbakker.com"]
  resources: ["safesecrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "list", "watch", "delete"]
