apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: safesecrets.janbakker.com
spec:
  group: janbakker.com
  names:
    kind: SafeSecret
    plural: safesecrets
    shortNames:
    - safes
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                safe-secret:
                  type: string

