apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: startpagina
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  # available in Openshift:
  storageClassName: efs-sc
  volumeMode: Filesystem
