apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-ss-configuration
data:
  master.conf: |
    maxmemory 400mb
    # maxmemory-policy allkeys-lru
    # maxclients 20000
    # timeout 300
    appendonly no
    # dbfilename dump.rdb
    dir /data
    bind 0.0.0.0
    # port 6379
    # protected-mode no
  slave.conf: |
    slaveof redis-ss-0.redis-service 6379
    # maxmemory 400mb
    # maxmemory-policy allkeys-lru
    # maxclients 20000
    # timeout 300
    # dir /data